create table fish_species (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(1000),
    image_url varchar(255),
    habitat_notes varchar(1000),
    active_times varchar(1000),
    strike_zone varchar(500),
    common_zones varchar(1000),
    favorite_lures varchar(1000),
    created_at timestamp(6) with time zone not null
);

create table fishing_spots (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(1000),
    latitude double precision not null,
    longitude double precision not null,
    water_type varchar(255) not null,
    favorite_species varchar(255),
    created_at timestamp(6) with time zone not null
);

create table lure_library_items (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    type varchar(255) not null,
    image_url varchar(255),
    difficulty varchar(255),
    effectiveness varchar(255),
    description varchar(1000),
    usage_notes varchar(1000),
    action_type varchar(500),
    ideal_conditions varchar(1000),
    created_at timestamp(6) with time zone not null
);

create table lures (
    id bigint generated by default as identity primary key,
    library_item_id bigint,
    name varchar(255) not null,
    type varchar(255) not null,
    color varchar(255),
    size varchar(255),
    weight double precision,
    brand varchar(255),
    notes varchar(1000),
    target_species varchar(255),
    water_type varchar(255) not null,
    active boolean,
    quantity integer,
    lure_condition varchar(255),
    personal_notes varchar(1000),
    favorite_for_species varchar(255),
    favorite_for_spot varchar(255),
    created_at timestamp(6) with time zone not null,
    constraint fk_lures_library_item foreign key (library_item_id) references lure_library_items (id)
);

create table fishing_plans (
    id bigint generated by default as identity primary key,
    spot_id bigint not null,
    planned_date date not null,
    planned_time time(6),
    target_species varchar(255) not null,
    water_clarity varchar(255) not null,
    water_level varchar(255) not null,
    notes varchar(1000),
    created_at timestamp(6) with time zone not null,
    constraint fk_plans_spot foreign key (spot_id) references fishing_spots (id)
);

create table fishing_sessions (
    id bigint generated by default as identity primary key,
    spot_id bigint not null,
    plan_id bigint,
    session_date date not null,
    start_time time(6),
    end_time time(6),
    status varchar(255),
    target_species varchar(255) not null,
    water_clarity varchar(255) not null,
    water_level varchar(255) not null,
    notes varchar(1000),
    success boolean,
    duration_minutes bigint,
    result_summary varchar(1000),
    final_notes varchar(1000),
    rating integer,
    created_at timestamp(6) with time zone not null,
    constraint fk_sessions_spot foreign key (spot_id) references fishing_spots (id),
    constraint fk_sessions_plan foreign key (plan_id) references fishing_plans (id)
);

create table ai_recommendations (
    id bigint generated by default as identity primary key,
    plan_id bigint,
    session_id bigint,
    recommendation_type varchar(255),
    version integer,
    context_json oid not null,
    raw_response oid not null,
    summary varchar(1000),
    lure_ranking_json oid,
    plan_a varchar(1000),
    plan_b varchar(1000),
    plan_c varchar(1000),
    avoid_json oid,
    confidence varchar(255),
    confidence_score integer,
    confidence_reason varchar(1000),
    latest boolean,
    superseded_at timestamp(6) with time zone,
    warnings_json oid,
    extra_json oid,
    created_at timestamp(6) with time zone not null,
    constraint fk_ai_recommendations_plan foreign key (plan_id) references fishing_plans (id),
    constraint fk_ai_recommendations_session foreign key (session_id) references fishing_sessions (id)
);

create table catches (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    species varchar(255) not null,
    quantity integer not null,
    size_cm double precision,
    weight_kg double precision,
    released boolean,
    notes varchar(1000),
    constraint fk_catches_session foreign key (session_id) references fishing_sessions (id)
);

create table fishing_plan_lures (
    id bigint generated by default as identity primary key,
    plan_id bigint not null,
    lure_id bigint not null,
    constraint fk_plan_lures_plan foreign key (plan_id) references fishing_plans (id),
    constraint fk_plan_lures_lure foreign key (lure_id) references lures (id)
);

create table session_events (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    event_time time(6),
    event_type varchar(255) not null,
    description varchar(1000),
    constraint fk_session_events_session foreign key (session_id) references fishing_sessions (id)
);

create table session_lures (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    lure_id bigint not null,
    used_from time(6),
    used_to time(6),
    result_notes varchar(1000),
    constraint fk_session_lures_session foreign key (session_id) references fishing_sessions (id),
    constraint fk_session_lures_lure foreign key (lure_id) references lures (id)
);

create table weather_snapshots (
    id bigint generated by default as identity primary key,
    plan_id bigint,
    session_id bigint,
    source varchar(255) not null,
    source_global_id_local integer,
    source_location_name varchar(255),
    source_latitude double precision,
    source_longitude double precision,
    forecast_date date,
    data_update timestamp(6) with time zone,
    weather_type_id integer,
    temperature_min double precision,
    temperature_max double precision,
    precipitation_probability double precision,
    wind_direction varchar(255),
    wind_speed_class integer,
    notes varchar(1000),
    captured_at timestamp(6) with time zone not null,
    constraint fk_weather_plan foreign key (plan_id) references fishing_plans (id),
    constraint fk_weather_session foreign key (session_id) references fishing_sessions (id)
);

create table recommendation_executions (
    id bigint generated by default as identity primary key,
    recommendation_id bigint not null,
    plan_id bigint,
    session_id bigint,
    recommendation_type varchar(255) not null,
    recommendation_version integer,
    recommendation_step varchar(255) not null,
    followed boolean not null,
    result varchar(255) not null,
    success boolean,
    rating integer,
    started_at time(6),
    ended_at time(6),
    notes varchar(1000),
    created_at timestamp(6) with time zone not null,
    constraint fk_rec_exec_recommendation foreign key (recommendation_id) references ai_recommendations (id),
    constraint fk_rec_exec_plan foreign key (plan_id) references fishing_plans (id),
    constraint fk_rec_exec_session foreign key (session_id) references fishing_sessions (id)
);

create index idx_fish_species_name on fish_species (name);
create index idx_fish_species_strike_zone on fish_species (strike_zone);
create index idx_fish_species_created_at on fish_species (created_at);

create index idx_spots_name on fishing_spots (name);
create index idx_spots_water_type on fishing_spots (water_type);
create index idx_spots_favorite_species on fishing_spots (favorite_species);
create index idx_spots_created_at on fishing_spots (created_at);

create index idx_lure_library_name on lure_library_items (name);
create index idx_lure_library_type on lure_library_items (type);
create index idx_lure_library_difficulty on lure_library_items (difficulty);
create index idx_lure_library_effectiveness on lure_library_items (effectiveness);
create index idx_lure_library_created_at on lure_library_items (created_at);

create index idx_lures_name on lures (name);
create index idx_lures_type on lures (type);
create index idx_lures_water_type on lures (water_type);
create index idx_lures_target_species on lures (target_species);
create index idx_lures_brand on lures (brand);
create index idx_lures_library_item on lures (library_item_id);
create index idx_lures_active on lures (active);
create index idx_lures_quantity on lures (quantity);
create index idx_lures_condition on lures (lure_condition);
create index idx_lures_created_at on lures (created_at);

create index idx_plans_spot on fishing_plans (spot_id);
create index idx_plans_date on fishing_plans (planned_date);
create index idx_plans_target_species on fishing_plans (target_species);
create index idx_plans_water_clarity on fishing_plans (water_clarity);
create index idx_plans_water_level on fishing_plans (water_level);
create index idx_plans_created_at on fishing_plans (created_at);

create index idx_sessions_spot on fishing_sessions (spot_id);
create index idx_sessions_plan on fishing_sessions (plan_id);
create index idx_sessions_date on fishing_sessions (session_date);
create index idx_sessions_status on fishing_sessions (status);
create index idx_sessions_target_species on fishing_sessions (target_species);
create index idx_sessions_success on fishing_sessions (success);
create index idx_sessions_rating on fishing_sessions (rating);
create index idx_sessions_created_at on fishing_sessions (created_at);

create index idx_ai_rec_plan_type_latest on ai_recommendations (plan_id, recommendation_type, latest);
create index idx_ai_rec_session_type_latest on ai_recommendations (session_id, recommendation_type, latest);
create index idx_ai_rec_plan_type_version on ai_recommendations (plan_id, recommendation_type, version);
create index idx_ai_rec_session_type_version on ai_recommendations (session_id, recommendation_type, version);
create index idx_ai_rec_created_at on ai_recommendations (created_at);

create index idx_catches_session on catches (session_id);
create index idx_catches_species on catches (species);

create index idx_plan_lures_plan on fishing_plan_lures (plan_id);
create index idx_plan_lures_lure on fishing_plan_lures (lure_id);

create index idx_session_events_session on session_events (session_id);
create index idx_session_events_type on session_events (event_type);
create index idx_session_events_time on session_events (event_time);

create index idx_session_lures_session on session_lures (session_id);
create index idx_session_lures_lure on session_lures (lure_id);
create index idx_session_lures_used_from on session_lures (used_from);

create index idx_weather_plan on weather_snapshots (plan_id);
create index idx_weather_session on weather_snapshots (session_id);
create index idx_weather_location on weather_snapshots (source_global_id_local);
create index idx_weather_forecast_date on weather_snapshots (forecast_date);
create index idx_weather_captured_at on weather_snapshots (captured_at);

create index idx_rec_exec_recommendation on recommendation_executions (recommendation_id);
create index idx_rec_exec_plan on recommendation_executions (plan_id);
create index idx_rec_exec_session on recommendation_executions (session_id);
create index idx_rec_exec_step on recommendation_executions (recommendation_step);
create index idx_rec_exec_followed on recommendation_executions (followed);
create index idx_rec_exec_success on recommendation_executions (success);
create index idx_rec_exec_created_at on recommendation_executions (created_at);
