update catches
set lure_library_item_id = null
where lure_library_item_id is not null;

update lures
set library_item_id = null
where library_item_id is not null;

delete from lure_library_items;
delete from fish_species;

insert into fish_species (
    name,
    water_environment,
    description,
    image_url,
    habitat_notes,
    active_times,
    strike_zone,
    common_zones,
    favorite_lures,
    created_at
) values
(
    'Barbel',
    'FRESHWATER',
    'Barbel (Barbus barbus) e um peixe de rio associado a correntes e fundos de cascalho. Alimenta-se sobretudo junto ao fundo.',
    '/demo/images/fish/freshwater/barbel.png',
    'Rios medios e grandes com corrente, cascalho, pedra e margens com sombra. Pode ocupar zonas mais lentas no inverno.',
    'Principalmente ao amanhecer e ao entardecer; juvenis podem alimentar-se durante o dia.',
    'bottom, current, structure',
    'current, rocky-areas, deep-water, structures',
    'Grub, Jig, Spoon',
    now()
),
(
    'Black Bass',
    'FRESHWATER',
    'Black bass (Micropterus salmoides) e um predador de agua doce que procura presas junto a cobertura, estruturas e margens tranquilas.',
    '/demo/images/fish/freshwater/black-bass.png',
    'Lagos, albufeiras, remansos e margens com vegetacao, troncos ou pedra; evita regra geral correntes fortes.',
    'Amanhecer e entardecer; pode atacar junto a cobertura durante o dia.',
    'surface, mid-water, bottom, vegetation, structure',
    'shallows, vegetation, structures, drop-offs, rocky-areas',
    'Senko, Crankbait, Spinnerbait, Frog, Jerkbait',
    now()
),
(
    'Brown Trout',
    'FRESHWATER',
    'Brown trout (Salmo trutta) e uma truta associada a agua fria, limpa e bem oxigenada, com comportamento territorial em muitos rios.',
    '/demo/images/fish/freshwater/brown-trout.png',
    'Ribeiros e rios frios, correntes, pedras, pocos e entradas de afluentes. Procura abrigo atras de pedras e nas margens.',
    'Manha e fim de tarde; a atividade pode aumentar durante eclosoes de insetos e ceu nublado.',
    'mid-water, bottom, current, bank',
    'current, rocky-areas, deep-water, structures',
    'Jerkbait, Spoon, Grub',
    now()
),
(
    'European Catfish',
    'FRESHWATER',
    'European catfish (Silurus glanis) e um grande predador de agua doce, geralmente associado a zonas fundas e de pouca luz.',
    '/demo/images/fish/freshwater/european-catfish.png',
    'Rios lentos, albufeiras e lagos com zonas fundas, lodo, troncos submersos e transicoes de profundidade.',
    'Entardecer, noite e primeiras horas; em agua quente pode alimentar-se tambem durante o dia.',
    'bottom, mid-water, structure',
    'deep-water, drop-offs, structures, open-water, current',
    'Swimbait, Grub, Jig, Spoon',
    now()
),
(
    'European Perch',
    'FRESHWATER',
    'European perch (Perca fluviatilis) e um predador oportunista que pode formar grupos e explorar varias profundidades.',
    '/demo/images/fish/freshwater/european-perch.png',
    'Lagos, albufeiras, lagoas e rios de corrente moderada, junto a margens, pedra, vegetacao e quedas de profundidade.',
    'Amanhecer e entardecer; juvenis e grupos ativos podem alimentar-se durante o dia.',
    'mid-water, bottom, structure, vegetation',
    'shallows, drop-offs, vegetation, rocky-areas, open-water',
    'Grub, Jerkbait, Spoon, Jig',
    now()
),
(
    'Pike',
    'FRESHWATER',
    'Pike (Esox lucius) e um predador de emboscada que usa a vegetacao e outras estruturas para surpreender presas.',
    '/demo/images/fish/freshwater/pike.png',
    'Lagos, albufeiras e rios lentos com canas, plantas aquaticas, margens abrigadas e transicoes para agua mais funda.',
    'Amanhecer e entardecer; dias nublados podem prolongar a atividade perto da cobertura.',
    'surface, mid-water, vegetation, structure',
    'vegetation, shallows, structures, drop-offs, open-water',
    'Spinnerbait, Jerkbait, Swimbait, Spoon, Frog',
    now()
),
(
    'Pike-perch',
    'FRESHWATER',
    'Pike-perch (Sander lucioperca) e um predador que tolera agua turva e procura frequentemente zonas fundas e transicoes.',
    '/demo/images/fish/freshwater/pike-perch.png',
    'Lagos, albufeiras e rios com fundos de areia ou cascalho, quedas de profundidade, pedra e corrente moderada.',
    'Crepusculo, noite e periodos de pouca luz; durante o dia tende a permanecer mais fundo.',
    'bottom, mid-water, structure',
    'deep-water, drop-offs, rocky-areas, open-water, current',
    'Jerkbait, Shad, Grub, Jig',
    now()
),
(
    'Rainbow Trout',
    'FRESHWATER',
    'Rainbow trout (Oncorhynchus mykiss) e uma truta de agua fria que responde a insetos, pequenos peixes e apresentacoes discretas.',
    '/demo/images/fish/freshwater/rainbow-trout.png',
    'Rios, ribeiros, lagos e massas de agua fria e oxigenada, junto a correntes, pedra, margens e entradas de agua.',
    'Durante o dia, com boas janelas ao amanhecer, ao entardecer e durante atividade de insetos.',
    'surface, mid-water, bottom, current',
    'current, rocky-areas, structures, shallows',
    'Spoon, Jerkbait, Grub',
    now()
),
(
    'European Anchovy',
    'SALTWATER',
    'European anchovy (Engraulis encrasicolus) e um peixe pelagico que forma grandes cardumes e pode aproximar-se de zonas costeiras e estuarios.',
    '/demo/images/fish/saltwater/anchovy.png',
    'Agua costeira, estuarios e mar aberto, normalmente em cardumes e associado a zonas com plancton e alimento disponivel.',
    'A atividade varia com a luz, a temperatura, as correntes e a concentracao de alimento; procure cardumes quando estao junto a superficie.',
    'surface, mid-water, open-water',
    'open-water, shallows, current',
    'Spoon, Shad, Jerkbait',
    now()
),
(
    'Atlantic Mackerel',
    'SALTWATER',
    'Atlantic mackerel (Scomber scombrus) e um peixe pelagico rapido que se desloca em cardumes e segue concentracoes de alimento.',
    '/demo/images/fish/saltwater/atlantic-mackerel.png',
    'Costa e plataforma continental, geralmente em agua aberta, junto a correntes, cardumes de forragem e mudancas de profundidade.',
    'Procure atividade quando ha forragem; amanhecer e fim de tarde sao janelas praticas, sem substituir a leitura do mar.',
    'surface, mid-water, open-water',
    'open-water, current, shallows',
    'Spoon, Jerkbait, Shad',
    now()
),
(
    'Atlantic Chub Mackerel',
    'SALTWATER',
    'Atlantic chub mackerel (Scomber colias) e um peixe pelagico de cardume, comum em aguas temperadas e quentes do Atlantico.',
    '/demo/images/fish/saltwater/chub-mackerel.png',
    'Aguas costeiras e de plataforma, junto a cardumes, correntes e zonas onde se concentram pequenos peixes e crustaceos.',
    'A atividade depende da forragem e das correntes; acompanhe sinais de peixe e aves antes de escolher a camada de agua.',
    'surface, mid-water, open-water',
    'open-water, current, shallows',
    'Spoon, Jerkbait, Shad',
    now()
),
(
    'Meagre',
    'SALTWATER',
    'Meagre (Argyrosomus regius), tambem conhecido como corvina, e um predador costeiro e estuarino que persegue peixe e crustaceos.',
    '/demo/images/fish/saltwater/croaker.png',
    'Zonas costeiras, estuarios e plataforma, perto do fundo, canais, desembocaduras, pedra e mudancas de profundidade.',
    'Amanhecer, entardecer e mudancas de mare sao boas janelas; a atividade depende da temperatura e da forragem local.',
    'bottom, mid-water, structure',
    'shallows, deep-water, drop-offs, current, structures',
    'Jerkbait, Swimbait, Spoon, Jig',
    now()
),
(
    'European Sea Bass',
    'SALTWATER',
    'European sea bass (Dicentrarchus labrax), ou robalo, e um predador costeiro que explora rebentacao, correntes e estuarios.',
    '/demo/images/fish/saltwater/sea-bass.png',
    'Costa rochosa, praias, barras, estuarios, canais e zonas de corrente onde pequenos peixes e crustaceos ficam concentrados.',
    'Amanhecer, entardecer e periodos de menor luz; as mares e a corrente podem ser mais importantes do que o relogio.',
    'surface, mid-water, bottom, structure',
    'shallows, rocky-areas, current, structures, open-water',
    'Jerkbait, Shad, Swimbait, Spoon',
    now()
);

insert into lure_library_items (
    name,
    type,
    image_url,
    difficulty,
    effectiveness,
    description,
    usage_notes,
    action_type,
    ideal_conditions,
    action_icon_url,
    action_image_url,
    created_at
) values
(
    'Crankbait',
    'Crankbait',
    '/demo/images/lures/crankbait.png',
    'Medium',
    'High',
    'Lure de corpo rigido com pala que gera vibracao e permite procurar agua rapidamente.',
    'Lance junto a pedra, madeira ou margens e varie a velocidade. Deixe a pala tocar de forma controlada na estrutura.',
    'Retrieve continuo com pausas curtas',
    'Agua com alguma cor, vento leve, peixe ativo e zonas com estrutura.',
    '/demo/images/lure-action-icons/crank-retrieve-icon.png',
    '/demo/images/lure-actions/crank-retrieve.png',
    now()
),
(
    'Frog',
    'Topwater',
    '/demo/images/lures/frog.png',
    'Medium',
    'High',
    'Lure de superficie pensada para passar sobre vegetacao e provocar ataques de peixes predadores.',
    'Trabalhe devagar sobre plantas e junto a coberturas. Aguarde um instante depois do ataque antes de ferrar.',
    'Pops curtos, puxoes e pausas',
    'Pouca ondulacao, pouca luz, vegetacao densa e predadores a caçar perto da superficie.',
    '/demo/images/lure-action-icons/top-water-icon.png',
    '/demo/images/lure-actions/top-water.png',
    now()
),
(
    'Grub',
    'Soft bait',
    '/demo/images/lures/grub.png',
    'Easy',
    'High',
    'Vinil compacto com cauda vibratoria, util para pescar devagar junto ao fundo ou na coluna de agua.',
    'Use uma cabeca adequada e mantenha contacto com o fundo. Alterne arrasto, pequenos saltos e pausas.',
    'Arrasto lento e pequenos saltos',
    'Peixe pouco ativo, agua clara ou ligeiramente turva, fundo com pedra, areia ou cascalho.',
    '/demo/images/lure-action-icons/bottom-fishing-icon.png',
    '/demo/images/lure-actions/bottom-fishing.png',
    now()
),
(
    'Jerkbait',
    'Jerkbait',
    '/demo/images/lures/jerkbait.png',
    'Medium',
    'High',
    'Lure suspending ou flutuante que imita um peixe ferido com mudancas de direcao e pausas.',
    'Use toques de cana separados por pausas. Ajuste a cadencia a temperatura e ao nivel de atividade.',
    'Jerk, twitch e pausa',
    'Agua clara a ligeiramente turva, peixe predador em meia agua e temperaturas amenas.',
    '/demo/images/lure-action-icons/jerk-twitch-icon.png',
    '/demo/images/lure-actions/jerk-twitch.png',
    now()
),
(
    'Jig',
    'Jig',
    '/demo/images/lures/jig.png',
    'Medium',
    'High',
    'Lure compacta e versatil para pescar no fundo, na coluna de agua ou de forma vertical.',
    'Conte a descida e mantenha contacto com o fundo. Use levantamentos curtos e deixe a lure voltar a pousar.',
    'Jigging vertical e hops curtos',
    'Agua funda, corrente moderada, peixe junto ao fundo e estruturas isoladas.',
    '/demo/images/lure-action-icons/jigging-icon.png',
    '/demo/images/lure-actions/jigging.png',
    now()
),
(
    'Popper',
    'Topwater',
    '/demo/images/lures/popper.png',
    'Easy',
    'High',
    'Lure de superficie com boca concava que cria salpicos e som para chamar predadores.',
    'Use toques curtos e pausas. Aumente a pausa quando o peixe segue a lure sem atacar.',
    'Pops curtos e pausas',
    'Agua relativamente calma, amanhecer, entardecer e sinais de atividade na superficie.',
    '/demo/images/lure-action-icons/top-water-icon.png',
    '/demo/images/lure-actions/top-water.png',
    now()
),
(
    'Senko',
    'Soft bait',
    '/demo/images/lures/senko.png',
    'Easy',
    'High',
    'Vinil de perfil simples e queda natural, eficaz quando o peixe esta desconfiado ou pouco ativo.',
    'Deixe a lure cair junto a cobertura e faça pequenos movimentos. Muitas picadas acontecem durante a queda ou a pausa.',
    'Queda controlada, arrasto lento e pausas',
    'Agua clara, pouca corrente, pressao de pesca elevada e peixe junto a estruturas.',
    '/demo/images/lure-action-icons/bottom-fishing-icon.png',
    '/demo/images/lure-actions/bottom-fishing.png',
    now()
),
(
    'Shad',
    'Swimbait',
    '/demo/images/lures/shad.png',
    'Easy',
    'High',
    'Imitacao de pequeno peixe com cauda que produz uma vibracao regular durante a recuperacao.',
    'Recupere a velocidade constante ou perto do fundo. Use pausas junto a quedas, pedra e margens.',
    'Retrieve constante e pausas',
    'Predadores a caçar peixe forrageiro, agua clara a ligeiramente turva e corrente moderada.',
    '/demo/images/lure-action-icons/crank-retrieve-icon.png',
    '/demo/images/lure-actions/crank-retrieve.png',
    now()
),
(
    'Spinner',
    'Spinner',
    '/demo/images/lures/spinner.png',
    'Easy',
    'Medium',
    'Lure com uma lamina rotativa que produz flash e vibracao durante a recuperacao.',
    'Recupere devagar o suficiente para a lamina trabalhar. Passe por margens, corrente e zonas com vegetacao aberta.',
    'Retrieve continuo com variacao de velocidade',
    'Agua com alguma cor, corrente leve, peixe ativo e pouca a media profundidade.',
    '/demo/images/lure-action-icons/crank-retrieve-icon.png',
    '/demo/images/lure-actions/crank-retrieve.png',
    now()
),
(
    'Spinnerbait',
    'Spinnerbait',
    '/demo/images/lures/spinnerbait.png',
    'Medium',
    'High',
    'Lure com uma ou mais laminas, pensada para cobrir agua e passar perto de cobertura sem prender facilmente.',
    'Lance para junto da estrutura e recupere a velocidade constante. Varie a profundidade com a contagem da queda.',
    'Slow roll e retrieve continuo',
    'Agua turva ou com vento, vegetacao, madeira, pedra e predadores em atividade.',
    '/demo/images/lure-action-icons/crank-retrieve-icon.png',
    '/demo/images/lure-actions/crank-retrieve.png',
    now()
),
(
    'Spoon',
    'Spoon',
    '/demo/images/lures/spoon.png',
    'Easy',
    'High',
    'Lure metalica que reflete luz e oscila durante a queda e a recuperacao.',
    'Alterne recuperacao constante, pausas e pequenas aceleracoes. Controle a profundidade pela contagem da queda.',
    'Retrieve, flutter na queda e pausas',
    'Agua aberta, corrente, vento leve e predadores a caçar peixe pequeno.',
    '/demo/images/lure-action-icons/crank-retrieve-icon.png',
    '/demo/images/lure-actions/crank-retrieve.png',
    now()
),
(
    'Swimbait',
    'Swimbait',
    '/demo/images/lures/swimbait.png',
    'Medium',
    'High',
    'Imitacao de peixe com perfil natural, disponivel em apresentacoes de superficie, meia agua ou fundo.',
    'Recupere devagar e mantenha a lure na camada onde o peixe esta. Use pausas junto a cobertura e quedas.',
    'Retrieve lento, pausas e mudanca de profundidade',
    'Predadores grandes, agua clara a ligeiramente turva e presenca de peixe forrageiro.',
    '/demo/images/lure-action-icons/crank-retrieve-icon.png',
    '/demo/images/lure-actions/crank-retrieve.png',
    now()
),
(
    'Whopper Plopper',
    'Topwater',
    '/demo/images/lures/whopper-plooper.png',
    'Easy',
    'High',
    'Lure de superficie com cauda rotativa que cria turbulencia e som durante uma recuperacao simples.',
    'Recupere a velocidade constante junto a margens, entradas de agua e zonas de sombra. Varie a velocidade se nao houver ataques.',
    'Retrieve continuo na superficie',
    'Pouca a media ondulacao, baixa luz, agua quente e predadores a caçar no topo.',
    '/demo/images/lure-action-icons/top-water-icon.png',
    '/demo/images/lure-actions/top-water.png',
    now()
);
